Repository Tailormap/tailormap-viewer, pull requests merged in 2022-03, with the labels that each got.

#54 HTM-187: Added zoom in/out buttons
  projects/api/package.json
  projects/core/assets/imgs/minimize.svg
  projects/core/assets/imgs/minus.svg
  projects/core/assets/imgs/plus.svg
  projects/core/assets/tailormap-styles.css
  projects/core/package.json
  projects/core/src/lib/components/components.module.ts
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
  projects/core/src/lib/components/zoom-buttons/index.ts
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.css
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.html
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.spec.ts
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.ts
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.module.ts
  projects/core/src/lib/pages/viewer-app/viewer-app.component.css
  projects/core/src/lib/pages/viewer-app/viewer-app.component.html
  projects/map/package.json
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/models/index.ts
  projects/map/src/lib/models/map-resolution.model.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
  projects/shared/package.json
  projects/shared/src/lib/components/dialog/dialog.component.css
  projects/shared/src/lib/components/dialog/dialog.component.html
  projects/shared/src/lib/components/dialog/dialog.component.ts
  projects/shared/src/lib/components/snackbar-message/snack-bar-message.component.spec.ts
  projects/shared/src/lib/components/tree-node-layer/tree-node-layer.component.ts
  projects/shared/src/lib/components/tree/tree.component.spec.ts
  projects/shared/src/lib/directives/auto-focus.directive.spec.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#55 compose file updates
  docker-compose-cd.yml
  docker-compose-pr.yml
  docker-compose.yml
Labels: enhancement

#56 [HTM-240] new datadump after loading WMS / WFS and JDBC sources from HTM-245
  docker/db/docker-entrypoint-initdb.d/3-dump.sql.script
  docker/db/docker-entrypoint-initdb.d/3-load-data.sh
Labels: enhancement

#57 HTM-77: Zoom to initial extent button
  projects/core/assets/imgs/minus.svg
  projects/core/assets/imgs/plus.svg
  projects/core/assets/imgs/zoom_max.svg
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.css
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.html
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.spec.ts
  projects/core/src/lib/components/zoom-buttons/zoom-buttons.component.ts
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#59 [HTM-243] add extra crs parameter to features call
  projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
  projects/api/src/lib/services/tailormap-api-v1.service.ts
Labels: enhancement

#60 HTM-145: Show highlight of currently selected feature info feature
  projects/api/src/lib/models/feature.model.ts
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.spec.ts
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
  projects/core/src/lib/components/feature-info/feature-info.service.spec.ts
  projects/core/src/lib/components/feature-info/feature-info.service.ts
  projects/core/src/lib/components/feature-info/feature-info/feature-info.component.spec.ts
  projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
  projects/core/src/lib/components/feature-info/helpers/feature-info.helper.ts
  projects/core/src/lib/components/feature-info/models/feature-info-column-metadata.model.ts
  projects/core/src/lib/components/feature-info/models/feature-info-feature.model.ts
  projects/core/src/lib/components/feature-info/models/feature-info-response.model.ts
  projects/core/src/lib/components/feature-info/models/feature-info.model.ts
  projects/core/src/lib/components/feature-info/state/feature-info.actions.ts
  projects/core/src/lib/components/feature-info/state/feature-info.reducer.spec.ts
  projects/core/src/lib/components/feature-info/state/feature-info.reducer.ts
  projects/core/src/lib/components/feature-info/state/feature-info.selectors.ts
  projects/core/src/lib/components/feature-info/state/feature-info.state.ts
  projects/core/src/lib/components/toc/toc/toc.component.spec.ts
  projects/core/src/lib/pages/viewer-app/viewer-app.component.ts
  projects/core/src/lib/shared/helpers/feature.helper.ts
  projects/map/src/lib/helpers/map-style.helper.ts
  projects/map/src/lib/helpers/ol-layer-types.helper.ts
  projects/map/src/lib/helpers/ol-layer.helper.ts
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/models/index.ts
  projects/map/src/lib/models/layer-manager.model.ts
  projects/map/src/lib/models/map-style.model.ts
  projects/map/src/lib/models/ol-map-style.type.ts
  projects/map/src/lib/openlayers-map/open-layers-layer-manager.ts
Labels: enhancement

#63 HTM-257 Update tailormap-db dump with current state from snapshot.b3pnl / h02
  docker/db/docker-entrypoint-initdb.d/3-dump.sql.script
  docker/db/docker-entrypoint-initdb.d/3-load-data.sh
Labels: infrastucture

#64 Fixes highlight feature bugs
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
  projects/core/src/lib/components/feature-info/feature-info.service.ts
  projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
  projects/core/src/lib/components/feature-info/state/feature-info.reducer.ts
  projects/core/src/lib/components/feature-info/state/feature-info.selectors.ts
  projects/map/src/lib/map-service/map.service.ts
Labels: bug

#65 Added linting rules to prohibit import from own project & openlayers
  .eslint-custom-rules.js
  angular.json
  projects/api/.eslintrc.js
  projects/app/.eslintrc.js
  projects/core/.eslintrc.js
  projects/core/src/lib/components/map-controls/map-controls.component.spec.ts
  projects/map/.eslintrc.js
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
  projects/shared/.eslintrc.js
Labels: enhancement
