Repository Tailormap/tailormap-viewer, pull requests merged in 2022-09, with the labels that each got.

#150 Bump OpenLayers from 7.0.0 to 7.1.0
  package-lock.json
  package.json
Labels: dependencies

#151 [HTM-451][HTM-452] use as-is sorting for the feature info rendering
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.spec.ts
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
  projects/core/src/lib/components/feature-info/helpers/feature-info.helper.ts
  projects/core/src/lib/components/feature-info/models/feature-info.model.ts
  projects/core/src/lib/components/feature-info/state/feature-info.selectors.ts
  projects/core/src/lib/map/state/map.selectors.ts
  projects/shared/src/lib/helpers/array.helper.spec.ts
  projects/shared/src/lib/helpers/array.helper.ts
Labels: bug, enhancement

#152 [HTM-332] Increase the default buffer distance multiplier from 4 to 10
  projects/core/src/lib/components/feature-info/feature-info.service.ts
Labels: bug, enhancement

#144 Add legend to PDF
  projects/api/src/lib/models/service-protocol.enum.ts
  projects/core/src/lib/components/legend/legend/legend.component.ts
  projects/core/src/lib/components/legend/services/legend.service.ts
  projects/core/src/lib/components/print/print/print.component.html
  projects/core/src/lib/components/print/print/print.component.spec.ts
  projects/core/src/lib/components/print/print/print.component.ts
  projects/core/src/lib/map/services/application-map.service.ts
  projects/core/src/lib/map/state/map.selectors.ts
  projects/core/src/lib/services/map-pdf/map-pdf.service.ts
  projects/core/src/lib/shared/helpers/image.helper.ts
Labels: enhancement

#159 HTM-377: Toggle all layers visibility
  projects/core/assets/imgs/check_all.svg
  projects/core/assets/imgs/uncheck_all.svg
  projects/core/src/lib/components/toc/toc.module.ts
  projects/core/src/lib/components/toc/toc/toc.component.css
  projects/core/src/lib/components/toc/toc/toc.component.html
  projects/core/src/lib/components/toc/toggle-all-layers-button/toggle-all-layers-button.component.css
  projects/core/src/lib/components/toc/toggle-all-layers-button/toggle-all-layers-button.component.html
  projects/core/src/lib/components/toc/toggle-all-layers-button/toggle-all-layers-button.component.spec.ts
  projects/core/src/lib/components/toc/toggle-all-layers-button/toggle-all-layers-button.component.ts
  projects/core/src/lib/map/state/map.actions.ts
  projects/core/src/lib/map/state/map.reducer.spec.ts
  projects/core/src/lib/map/state/map.reducer.ts
  projects/core/src/lib/map/state/map.selectors.ts
  projects/shared/src/lib/directives/index.ts
  projects/shared/src/lib/directives/tooltip.directive.ts
  projects/shared/src/lib/services/icons/icon.service.ts
  projects/shared/src/lib/shared.module.ts
Labels: enhancement

#161 HTM-148: Transform URL's in feature info to clickable links
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
  projects/shared/src/lib/directives/index.ts
  projects/shared/src/lib/directives/transform-urls.directive.spec.ts
  projects/shared/src/lib/directives/transform-urls.directive.ts
  projects/shared/src/lib/shared.module.ts
Labels: enhancement

#164 [HTM-472] Update title and add all the favicons and application tiles
  projects/app/src/android-icon-144x144.png
  projects/app/src/android-icon-192x192.png
  projects/app/src/android-icon-36x36.png
  projects/app/src/android-icon-48x48.png
  projects/app/src/android-icon-72x72.png
  projects/app/src/android-icon-96x96.png
  projects/app/src/apple-icon-114x114.png
  projects/app/src/apple-icon-120x120.png
  projects/app/src/apple-icon-144x144.png
  projects/app/src/apple-icon-152x152.png
  projects/app/src/apple-icon-180x180.png
  projects/app/src/apple-icon-57x57.png
  projects/app/src/apple-icon-60x60.png
  projects/app/src/apple-icon-72x72.png
  projects/app/src/apple-icon-76x76.png
  projects/app/src/apple-icon-precomposed.png
  projects/app/src/apple-icon.png
  projects/app/src/browserconfig.xml
  projects/app/src/favicon-16x16.png
  projects/app/src/favicon-32x32.png
  projects/app/src/favicon-96x96.png
  projects/app/src/favicon.ico
  projects/app/src/index.html
  projects/app/src/manifest.json
  projects/app/src/ms-icon-144x144.png
  projects/app/src/ms-icon-150x150.png
  projects/app/src/ms-icon-310x310.png
  projects/app/src/ms-icon-70x70.png
Labels: enhancement

#165 [HTM-470] Upgrade CI to latest/current Ubuntu and docker compose versions
  .github/workflows/cleanup-and-maintainance.yml
  .github/workflows/close-pr.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/test-and-deploy.yml
  README.md
  docker-compose-pr.yml
  docker/db/docker-entrypoint-initdb.d/3-load-data.sh
Labels: documentation, infrastucture

#169 HTM-462|HTM-461: Added attribute list UI for filtering + implement filtering
  package-lock.json
  package.json
  projects/api/src/lib/services/index.ts
  projects/api/src/lib/services/unique-values.service.ts
  projects/core/assets/imgs/filter_outline.svg
  projects/core/assets/tailormap-styles-form.css
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.css
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.spec.ts
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-filter/attribute-list-filter.component.css
  projects/core/src/lib/components/attribute-list/attribute-list-filter/attribute-list-filter.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-filter/attribute-list-filter.component.spec.ts
  projects/core/src/lib/components/attribute-list/attribute-list-filter/attribute-list-filter.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-identifier.ts
  projects/core/src/lib/components/attribute-list/attribute-list-paging-dialog/attribute-list-paging-dialog.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.css
  projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list.module.ts
  projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.spec.ts
  projects/core/src/lib/components/attribute-list/services/attribute-list-data.service.ts
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.css
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
  projects/core/src/lib/components/print/print/print.component.css
  projects/core/src/lib/components/print/print/print.component.html
  projects/core/src/lib/filter/attribute-filter/attribute-filter.component.css
  projects/core/src/lib/filter/attribute-filter/attribute-filter.component.html
  projects/core/src/lib/filter/attribute-filter/attribute-filter.component.spec.ts
  projects/core/src/lib/filter/attribute-filter/attribute-filter.component.ts
  projects/core/src/lib/filter/filter.module.ts
  projects/core/src/lib/filter/helpers/attribute-filter.helper.ts
  projects/core/src/lib/filter/models/attribute-filter-type.model.ts
  projects/core/src/lib/filter/services/filter.service.spec.ts
  projects/core/src/lib/filter/services/filter.service.ts
  projects/core/src/lib/filter/services/simple-attribute-filter.service.ts
  projects/map/src/lib/helpers/ol-layer.helper.ts
  projects/map/src/lib/openlayers-map/open-layers-layer-manager.ts
  projects/shared/src/lib/components/color-picker/color-picker.component.css
  projects/shared/src/lib/components/color-picker/color-picker.component.html
  projects/shared/src/lib/shared-imports.module.ts
Labels: enhancement

#172 Combine pull and up in 1 command
  .github/workflows/test-and-deploy.yml
Labels: infrastucture

#177 Revert to old docker-compose for pulling snapshot images on main branch deployment
  .github/workflows/test-and-deploy.yml
Labels: infrastucture

#178 HTM-478: Mobile screen fixes
  projects/core/assets/tailormap-styles.css
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.css
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.html
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.ts
  projects/core/src/lib/components/menubar/menubar-button/menubar-button.component.css
  projects/core/src/lib/components/menubar/menubar-panel/menubar-panel.component.html
  projects/core/src/lib/components/menubar/menubar-panel/menubar-panel.component.ts
  projects/core/src/lib/components/menubar/menubar.component.css
  projects/core/src/lib/components/menubar/menubar.component.html
  projects/core/src/lib/components/print/print/print.component.css
  projects/core/src/lib/components/toc/toc/toc.component.css
  projects/core/src/lib/pages/viewer-app/viewer-app.component.css
  projects/shared/src/lib/components/color-picker/color-picker.component.ts
  projects/shared/src/lib/components/confirm-dialog/confirm-dialog.service.ts
  projects/shared/src/lib/components/dialog/dialog.component.html
  projects/shared/src/lib/components/dialog/dialog.component.ts
  projects/shared/src/lib/components/dialog/dialog.service.ts
  projects/shared/src/lib/components/panel-resizer/panel-resizer.component.ts
  projects/shared/src/lib/components/tree/tree.component.ts
  projects/shared/src/lib/helpers/browser.helper.ts
  projects/shared/src/lib/helpers/css.helper.ts
  projects/shared/src/lib/helpers/index.ts
  projects/shared/src/lib/shared.module.ts
Labels: enhancement, hacktoberfest-accepted
