Repository Tailormap/tailormap-viewer, pull requests merged in 2022-10, with the labels that each got.

#180 [security] Don't run container as root, add Trivy scanner to scan built images
  .github/workflows/trivy.yml
  Dockerfile
  docker/db/Dockerfile
Labels: enhancement, infrastucture, security, hacktoberfest-accepted

#179 [HTM-488] Do not assume geoserver hidpi serverType for generic services
  projects/map/src/lib/helpers/ol-layer.helper.ts
Labels: bug

#183 HTM-493: Transform image-like links to <img> tags
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
  projects/shared/src/lib/directives/transform-urls.directive.spec.ts
  projects/shared/src/lib/directives/transform-urls.directive.ts
Labels: enhancement

#184 HTM-490: Fixed inconsistencies with selected row & highlighted feature
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.html
  projects/core/src/lib/components/attribute-list/attribute-list-table/attribute-list-table.component.ts
  projects/core/src/lib/components/attribute-list/models/attribute-list-data.model.ts
  projects/core/src/lib/components/attribute-list/models/attribute-list-row.model.ts
  projects/core/src/lib/components/attribute-list/services/attribute-list-data.service.ts
  projects/core/src/lib/components/attribute-list/state/attribute-list.actions.ts
  projects/core/src/lib/components/attribute-list/state/attribute-list.effects.ts
  projects/core/src/lib/components/attribute-list/state/attribute-list.reducer.ts
  projects/core/src/lib/components/attribute-list/state/attribute-list.selectors.ts
  projects/core/src/lib/components/attribute-list/state/attribute-list.state.ts
  projects/core/src/lib/components/attribute-list/state/mocks/attribute-list-state-test-data.ts
Labels: bug

#181 [HTM-480] Add hidpi settings and services
  docker/db/docker-entrypoint-initdb.d/3-dump.sql.script
Labels: enhancement, hacktoberfest-accepted

#185 HTM-489: Added search trough PDOK | Nomatim
  projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
  projects/core/assets/tailormap-styles.css
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.css
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.html
  projects/core/src/lib/components/toolbar/measure/measure.component.css
  projects/core/src/lib/components/toolbar/measure/measure.component.html
  projects/core/src/lib/components/toolbar/simple-search/index.ts
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.css
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.html
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.spec.ts
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.ts
  projects/core/src/lib/components/toolbar/simple-search/simple-search.module.ts
  projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts
  projects/core/src/lib/components/toolbar/toolbar.module.ts
  projects/core/src/lib/components/toolbar/zoom-buttons/zoom-buttons.component.css
  projects/core/src/lib/components/toolbar/zoom-buttons/zoom-buttons.component.html
  projects/core/src/lib/pages/viewer-app/viewer-app.component.css
  projects/core/src/lib/pages/viewer-app/viewer-app.component.html
  projects/map/src/lib/helpers/feature.helper.ts
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/models/index.ts
  projects/map/src/lib/models/projection-codes.enum.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
  projects/shared/src/lib/directives/transform-urls.directive.ts
  projects/shared/src/lib/shared-imports.module.ts
Labels: enhancement

#186 HTM-501: Show 'no results found' message + search status
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.css
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.html
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.ts
Labels: bug

#187 Composer updates, add Renovate workflow
  .github/renovate.json
  .github/workflows/renovate.yml
  docker-compose.yml
Labels: enhancement, infrastucture, hacktoberfest-accepted

#190 [HTM-506] Update the docker compose file to make running release versions possible
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  Dockerfile
  README.md
  docker-compose.yml
  docker/db/Dockerfile
Labels: infrastucture, hacktoberfest-accepted

#191 Optimized background layer selector for smaller screens
  projects/core/src/lib/components/background-layer-toggle/background-layer-toggle.component.html
  projects/core/src/lib/pages/viewer-app/viewer-app.component.css
  projects/shared/src/lib/components/split-button/split-button.component.css
  projects/shared/src/lib/components/split-button/split-button.component.html
  projects/shared/src/lib/components/split-button/split-button.component.ts
Labels: enhancement

#189 Bump NodeJS from 16.17.1 to 16.18.0
  .github/workflows/test-and-deploy.yml
  Dockerfile
Labels: infrastucture, dependencies, hacktoberfest-accepted

#199 Apply lazy loading for Sentry. Don't load if DSN is not set
  projects/app/src/main.ts
  projects/core/src/lib/core.module.ts
Labels: enhancement

#198 HTM-534: Fix map build by lazy loading NPM packages instead of own code
  projects/core/src/lib/components/print/print/print.component.ts
  projects/core/src/lib/services/map-pdf/map-pdf.service.ts
  projects/map/src/lib/openlayers-map/openlayers-map-image-exporter.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
Labels: bug

#200 Fixed publishing NPM packages
  angular.json
  bin/publish-all.js
  bin/publish-new-release.js
  bin/shared.js
  package.json
  projects/api/package.json
  projects/core/package.json
  projects/core/src/lib/core.module.ts
  projects/core/src/public-api.ts
  projects/map/package.json
  projects/map/src/lib/openlayers-map/openlayers-map-image-exporter.ts
  projects/map/src/public-api.ts
  projects/shared/package.json
  projects/shared/src/lib/shared-imports.module.ts
Labels: infrastucture

#204 Don't run scheduled workflows during the weekend
  .github/dependabot.yml
  .github/workflows/cleanup-and-maintainance.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-drafter.yml
  .github/workflows/renovate.yml
  .github/workflows/trivy.yml
Labels: infrastucture, hacktoberfest-accepted

#206 Fix CVE-2022-32221, CVE-2022-42915 and CVE-2022-42916 and setup proper timezone
  Dockerfile
  docker/db/Dockerfile
Labels: infrastucture, dependencies, security
