Repository Tailormap/tailormap-viewer, pull requests merged in 2022-11, with the labels that each got.

#210 HTM-523: Always register proj4 to OpenLayers
  projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts
  projects/map/src/lib/helpers/projections.helper.ts
Labels: bug

#209 [HTM-516] Build platform independent images
  .github/workflows/test-and-deploy.yml
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#211 Deny any GPL licenses / check current licenses
  .github/workflows/test-and-deploy.yml
Labels: documentation

#213 Bump loader-utils from 2.0.2 to 2.0.3 to resolve CVE-2022-37601
  package-lock.json
Labels: dependencies, security

#214 Describe local-only builds and fix Trivy workflow
  .github/workflows/trivy.yml
  Dockerfile
  README.md
  docker/db/Dockerfile
Labels: documentation, infrastucture, dependencies, security

#216 HTM-558: Show/hide components in viewer based on components config
  projects/api/package.json
  projects/api/src/lib/models/base-component-type.enum.ts
  projects/api/src/lib/models/index.ts
  projects/core/package.json
  projects/core/src/lib/components/attribute-list/attribute-list-content/attribute-list-content.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-filter/attribute-list-filter.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list-identifier.ts
  projects/core/src/lib/components/attribute-list/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  projects/core/src/lib/components/drawing/drawing-identifier.ts
  projects/core/src/lib/components/drawing/drawing-menu-button/drawing-menu-button.component.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.ts
  projects/core/src/lib/components/legend/legend-identifier.ts
  projects/core/src/lib/components/legend/legend-menu-button/legend-menu-button.component.ts
  projects/core/src/lib/components/legend/legend/legend.component.spec.ts
  projects/core/src/lib/components/legend/legend/legend.component.ts
  projects/core/src/lib/components/print/print-identifier.ts
  projects/core/src/lib/components/print/print-menu-button/print-menu-button.component.ts
  projects/core/src/lib/components/print/print/print.component.ts
  projects/core/src/lib/components/toc/toc-identifier.ts
  projects/core/src/lib/components/toc/toc-menu-button/toc-menu-button.component.ts
  projects/core/src/lib/components/toc/toc/toc.component.ts
  projects/core/src/lib/core.module.ts
  projects/core/src/lib/layout/base-layout/base-layout.component.css
  projects/core/src/lib/layout/base-layout/base-layout.component.html
  projects/core/src/lib/layout/base-layout/base-layout.component.spec.ts
  projects/core/src/lib/layout/base-layout/base-layout.component.ts
  projects/core/src/lib/layout/layout.module.ts
  projects/core/src/lib/pages/viewer-app/viewer-app.component.css
  projects/core/src/lib/pages/viewer-app/viewer-app.component.html
  projects/core/src/lib/pages/viewer-app/viewer-app.component.spec.ts
  projects/core/src/lib/state/core.selectors.ts
  projects/map/package.json
Labels: enhancement

#217 Bump NodeJS from 16.x to 18.x
  .github/workflows/test-and-deploy.yml
  Dockerfile
  README.md
  package-lock.json
  package.json
Labels: enhancement, dependencies

#218 [HTM-568] Override url from capabilities with url from app config to support proxying WMTS with KVP encoding
  projects/map/src/lib/helpers/ol-layer.helper.ts
Labels: enhancement

#226 Bump Sentry from 7.14.1 to 7.20.1
  package-lock.json
  package.json
Labels: dependencies

#232 [HTM-590] Fix hardcoded application id
  projects/core/src/lib/components/filter/services/create-filter.service.ts
Labels: bug
