Repository Tailormap/tailormap-viewer, pull requests merged in 2022-06, with the labels that each got.

#96 HTM-312: Add properties for line drawing
  angular.json
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.ts
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.css
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.spec.ts
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.ts
  projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
  projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
  projects/core/src/lib/components/drawing/state/drawing.selectors.ts
  projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
  projects/core/src/lib/components/toolbar/measure/measure.component.ts
  projects/map/src/lib/helpers/feature.helper.ts
  projects/map/src/lib/helpers/geometry-type.helper.ts
  projects/map/src/lib/helpers/map-size.helper.ts
  projects/map/src/lib/helpers/map-style.helper.ts
  projects/map/src/lib/models/map-style.model.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-drawing-tool.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-select-tool.ts
  projects/shared/src/lib/helpers/index.ts
  projects/shared/src/lib/helpers/style.helper.ts
  projects/shared/src/lib/services/icons/icon.service.ts
  projects/shared/src/lib/shared-imports.module.ts
Labels: enhancement

#97 HTM-313: Add option for pattern fill to polygon/circle
  projects/core/assets/tailormap-styles-form.css
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.css
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.css
  projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
  projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
  projects/map/src/lib/helpers/map-style.helper.ts
  projects/map/src/lib/models/map-style.model.ts
Labels: enhancement

#98 HTM-314: Add drawing buttons for square, rectangle, ellipse and star
  projects/core/assets/imgs/tools/draw_circle.svg
  projects/core/assets/imgs/tools/draw_ellipse.svg
  projects/core/assets/imgs/tools/draw_label.svg
  projects/core/assets/imgs/tools/draw_line.svg
  projects/core/assets/imgs/tools/draw_point.svg
  projects/core/assets/imgs/tools/draw_polygon.svg
  projects/core/assets/imgs/tools/draw_rectangle.svg
  projects/core/assets/imgs/tools/draw_square.svg
  projects/core/assets/imgs/tools/draw_star.svg
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.html
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.spec.ts
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.ts
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.css
  projects/core/src/lib/components/drawing/models/drawing-feature-type.enum.ts
  projects/map/src/lib/helpers/drawing.helper.ts
  projects/map/src/lib/models/tools/drawing-tool-config.model.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-drawing-tool.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#99 HTM-315: Added more styling options for labels + multi-line label
  projects/core/assets/imgs/style/bold.svg
  projects/core/assets/imgs/style/italic.svg
  projects/core/assets/tailormap-styles-form.css
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.html
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.ts
  projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
  projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
  projects/core/src/lib/components/drawing/state/drawing.reducer.ts
  projects/map/src/lib/helpers/map-style.helper.ts
  projects/map/src/lib/models/map-style.model.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#104 Update docker db image
  docker-compose.yml
  docker/db/Dockerfile
Labels: dependencies

#105 [HTM-395] Add a `hasAttributes` member to the API's AppLayer
  projects/api/src/lib/mock-data/tailormap-api.mock-data.ts
  projects/api/src/lib/models/app-layer.model.ts
  projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
Labels: enhancement

#106 [HTM-338] Only request feature info when layer has feature type / attributes
  projects/core/src/lib/components/feature-info/feature-info.service.spec.ts
  projects/core/src/lib/components/feature-info/feature-info.service.ts
  projects/core/src/lib/map/state/map.selectors.ts
Labels: bug

#107 [HTM-332] synchronize the featureinfo buffer distance with the default value from the API
  projects/core/src/lib/components/feature-info/feature-info.service.ts
Labels: bug

#108 [HTM-392] Add a touchend on the color divs so that you can choose colors on Android
  projects/shared/src/lib/components/color-picker/color-picker.component.html
Labels: bug

#110 HTM-326: Clean up vector layers on destroying
  projects/map/src/lib/openlayers-map/open-layers-layer-manager.ts
Labels: bug

#112 HTM-402: Toggle maximize icons for attribute-list
  projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.css
  projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.html
Labels: bug

#113 HTM-408: Fixed layer/legend ordering
  projects/core/src/lib/map/state/map.selectors.ts
Labels: bug

#114 HTM-405: Show size/coordinates for drawing objects
  projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
  projects/map/src/lib/helpers/map-style.helper.ts
Labels: bug
