Repository Tailormap/tailormap-viewer, pull requests merged in 2023-02, with the labels that each got.

#296 [HTM-675] Require CORS enabled or proxied services
  docker/db/docker-entrypoint-initdb.d/3-dump.sql.script
  projects/core/src/lib/map/services/application-map.service.ts
Labels: bug

#306 Only do npm builds on amd64
  .github/workflows/test-and-deploy.yml
  Dockerfile
  README.md
  docker-compose.yml
Labels: infrastucture

#311 ⬆️ Docker update: Update postgres Docker tag to v15.2
  docker-compose.yml
Labels: security, docker-update
