Repository Tailormap/tailormap-viewer, pull requests merged in 2023-01, with the labels that each got.

#267 Bump OpenLayers from 7.1.0 to 7.2.2
  package-lock.json
  package.json
Labels: dependencies

#287 Make sure dependabot updates nodejs runtime, update to latest stable …
  .github/workflows/test-and-deploy.yml
  Dockerfile
  docker/db/Dockerfile
  package-lock.json
  package.json
Labels: infrastucture

#290 [HTM-665] Fix vendor-specific legend parameters not added in layer details
  projects/core/src/lib/components/toc/toc-node-details/layer-details/layer-details.component.ts
  projects/core/src/lib/map/state/map.selectors.ts
Labels: bug

#291 [HTM-668] Display SVG URLs as images
  projects/shared/src/lib/pipes/htmlify.pipe.spec.ts
  projects/shared/src/lib/pipes/htmlify.pipe.ts
Labels: enhancement

#293 HTM-628: Do not set crossOrigin to anonymous
  docker/db/docker-entrypoint-initdb.d/3-dump.sql.script
  projects/core/src/lib/map/services/application-map.service.ts
Labels: bug
