Repository Tailormap/tailormap-viewer, pull requests merged in 2024-10, with the labels that each got.

#716 Use docker save/load instead of ghcr for continuous deployment
  .github/workflows/close-pr.yml
  .github/workflows/test-and-deploy.yml
Labels: infrastructure

#715 HTM-981: Change background-layer-toggle to show ellipsis when title is too long
  projects/shared/src/lib/components/split-button/split-button.component.css
  projects/shared/src/lib/components/split-button/split-button.component.html
  projects/shared/src/lib/components/split-button/split-button.component.spec.ts
Labels: enhancement

#722 HTM-1255: Add the possibility to define a schedule on a search index
  projects/admin-api/src/lib/models/search-index.model.ts
  projects/admin-api/src/lib/models/taskschedule.model.ts
Labels: enhancement

#730 HTM-1276: Bump Solr version from 9.6.1 to 9.7.0
  docker-compose.yml
Labels: dependency

#731 HTM-1277: Bump postgresql from postgres:15.7-alpine3.18 to postgres:15.8-alpine3.20
  docker-compose.yml
Labels: bug

#737 HTM-1294: Upgrade NodeJS runtime to 22.x (new LTS)
  .github/workflows/test-and-deploy.yml
  Dockerfile
  README.md
  package-lock.json
  package.json
Labels: dependency
