Repository Tailormap/tailormap-viewer, pull requests merged in 2024-02, with the labels that each got.

#558 Update Codecov action to v4
  .github/workflows/test-and-deploy.yml
Labels: infrastucture

#561 Do not navigate to same URL after error again to avoid infinite routing loop, fix navigating to empty URL
  bin/package-lock.json
  bin/package.json
  package.json
  projects/admin-core/src/lib/templates/admin-template/admin-template.component.ts
  projects/core/src/lib/services/navigation-error-router.service.ts
Labels: bug

#569 HTM-1011: Fix Dutch translation
  projects/core/assets/locale/messages.core.nl.xlf
Labels: bug

#567 HTM-1009: CRS for XYZ layer
  projects/admin-api/src/lib/models/geo-service-settings.model.ts
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-details/geo-service-details.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-form-dialog/geo-service-form-dialog.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.html
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.ts
Labels: enhancement

#568 Small catalog updates: allow empty feature source title, add map service label
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.html
  projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.spec.ts
  projects/admin-core/src/lib/catalog/feature-source-form/feature-source-form.component.ts
Labels: enhancement

#570 HTM-962: Override GeoTools' projection WKT with proj4js definition for EPSG:28992
  projects/map/src/lib/helpers/feature.helper.spec.ts
  projects/map/src/lib/helpers/projections.helper.ts
Labels: bug
