Repository Tailormap/tailormap-viewer, pull requests merged in 2024-09, with the labels that each got.

#698 HTM-1162: Show logfile
  projects/admin-core/assets/icons/admin/logs.svg
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/admin-core-routing.module.ts
  projects/admin-core/src/lib/admin-core.module.ts
  projects/admin-core/src/lib/pages/logs-page/logs-page.component.css
  projects/admin-core/src/lib/pages/logs-page/logs-page.component.html
  projects/admin-core/src/lib/pages/logs-page/logs-page.component.ts
  projects/admin-core/src/lib/pages/pages.module.ts
  projects/admin-core/src/lib/routes.ts
  projects/admin-core/src/lib/templates/admin-template/navigation/navigation.component.html
  projects/admin-core/src/lib/templates/admin-template/navigation/navigation.component.ts
Labels: enhancement

#700 HTM-1208: Add caching for Trivy
  .github/workflows/trivy.yml
Labels: infrastructure

#701 HTM-1205: Prevent creating Solr indexes for WFS feature types
  projects/admin-core/src/lib/catalog/feature-type-selector/feature-type-selector.component.ts
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.html
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
Labels: bug

#705 HTM-1215: Upload test results to Codecov
  .github/workflows/test-and-deploy.yml
Labels: infrastructure

#713 HTM-1237: Upgrade OpenLayers to 10.2.1
  jest.base.config.js
  package-lock.json
  package.json
Labels: dependency
