Repository Tailormap/tailormap-viewer, pull requests merged in 2024-11, with the labels that each got.

#747 ⛓️‍💥 HTM-1319: Replace Solr image in the Tailormap stack with the new image⛓️‍💥
  docker-compose.yml
Labels: enhancement, breaking

#738 HTM-1250: User interface to administer tasks
  projects/admin-api/src/lib/mock-data/tailormap-admin-api.mock-data.ts
  projects/admin-api/src/lib/models/index.ts
  projects/admin-api/src/lib/models/task-details.model.ts
  projects/admin-api/src/lib/models/task.model.ts
  projects/admin-api/src/lib/services/tailormap-admin-api-v1-mock.service.ts
  projects/admin-api/src/lib/services/tailormap-admin-api-v1-service.model.ts
  projects/admin-api/src/lib/services/tailormap-admin-api-v1.service.ts
  projects/admin-core/assets/icons/admin/task_failed.svg
  projects/admin-core/assets/icons/admin/task_running.svg
  projects/admin-core/assets/icons/admin/task_successful.svg
  projects/admin-core/assets/icons/admin/tasks.svg
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/admin-core-routing.module.ts
  projects/admin-core/src/lib/admin-core.module.ts
  projects/admin-core/src/lib/pages/pages.module.ts
  projects/admin-core/src/lib/pages/tasks-page/tasks-page.component.css
  projects/admin-core/src/lib/pages/tasks-page/tasks-page.component.html
  projects/admin-core/src/lib/pages/tasks-page/tasks-page.component.ts
  projects/admin-core/src/lib/routes.ts
  projects/admin-core/src/lib/tasks/services/task-monitoring.service.ts
  projects/admin-core/src/lib/tasks/state/tasks.actions.ts
  projects/admin-core/src/lib/tasks/state/tasks.effects.ts
  projects/admin-core/src/lib/tasks/state/tasks.reducer.ts
  projects/admin-core/src/lib/tasks/state/tasks.selectors.ts
  projects/admin-core/src/lib/tasks/state/tasks.state.ts
  projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.css
  projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.html
  projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.ts
  projects/admin-core/src/lib/tasks/task-details/task-details.component.css
  projects/admin-core/src/lib/tasks/task-details/task-details.component.html
  projects/admin-core/src/lib/tasks/task-details/task-details.component.spec.ts
  projects/admin-core/src/lib/tasks/task-details/task-details.component.ts
  projects/admin-core/src/lib/tasks/tasks-home/tasks-home.component.css
  projects/admin-core/src/lib/tasks/tasks-home/tasks-home.component.html
  projects/admin-core/src/lib/tasks/tasks-home/tasks-home.component.ts
  projects/admin-core/src/lib/tasks/tasks-list/tasks-list.component.css
  projects/admin-core/src/lib/tasks/tasks-list/tasks-list.component.html
  projects/admin-core/src/lib/tasks/tasks-list/tasks-list.component.spec.ts
  projects/admin-core/src/lib/tasks/tasks-list/tasks-list.component.ts
  projects/admin-core/src/lib/tasks/tasks.module.ts
  projects/admin-core/src/lib/templates/admin-template/navigation/navigation.component.ts
  projects/core/assets/locale/messages.core.de.xlf
  projects/core/assets/locale/messages.core.en.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/shared/assets/locale/messages.shared.de.xlf
  projects/shared/assets/locale/messages.shared.nl.xlf
Labels: enhancement

#758 HTM-1242: remove arm64 build instructions
  README.md
Labels: documentation

#767 Export Admin SSE service for use in plugins
  projects/admin-core/src/public-api.ts
Labels: enhancement

#766 Fixed issue where Milkdown editor blurred after typing
  projects/shared/src/lib/components/markdown-editor/markdown-editor.component.ts
  projects/shared/src/lib/components/markdown-editor/markdown-editor.service.ts
Labels: bug

#765 Added @ngrx/operators as dependency (used in effects)
  package-lock.json
  package.json
  projects/admin-core/package.json
  projects/core/package.json
Labels: dependency

#763 HTM-1324 (revised): Added translation for 'Description*'
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.css
  projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.html
  projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.ts
  projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.ts
  projects/api/src/lib/services/application-feature-switch.service.ts
Labels: enhancement
