Repository Tailormap/tailormap-viewer, pull requests merged in 2024-12, with the labels that each got.

#771 HTM-1352: update notification message
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/search-index/services/search-index.service.ts
Labels: bug

#773 HTM-1353: Add some production-ready Solr options
  docker-compose.yml
Labels: bug

#774 HTM-1326: fix PDOK Address search fails when SOLR search index query returns an error or SOLR is unavailable
  projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts
Labels: bug

#777 HTM-1354: Fixes issue in embedded viewer where search would break
  projects/core/src/lib/shared/components/dialog/dialog.service.ts
Labels: bug

#772 HTM-1350: Upgrade OpenLayers from 10.2.1 to 10.3.1 and Proj4js from 2.12.1 to 2.15.0
  jest.base.config.js
  package-lock.json
  package.json
Labels: dependency

#780 HTM-1292: Do not remove row when pressing <Enter>.
  projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.html
  projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.ts
Labels: bug

#781 Only update Markdown editor contents if content is changed
  projects/shared/src/lib/components/markdown-editor/markdown-editor.service.ts
  projects/shared/src/lib/components/markdown-editor/milkdown/milkdown-editor.component.ts
Labels: bug

#782 HTM-1234: Prevent root collapse. Expand/collapse levels below root
  projects/admin-core/src/lib/application/application-layer-tree/application-layer-tree.component.html
  projects/admin-core/src/lib/application/helpers/application-tree.helper.ts
  projects/shared/src/lib/components/tree/tree.component.html
  projects/shared/src/lib/components/tree/tree.component.ts
Labels: bug

#783 HTM-1368: Update SearchIndexModel and usage for API change
  projects/admin-api/src/lib/models/search-index-summary.model.ts
  projects/admin-api/src/lib/models/search-index.model.ts
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/search-index/search-index-create/search-index-create.component.ts
  projects/admin-core/src/lib/search-index/search-index-edit/search-index-edit.component.ts
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.html
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
  projects/admin-core/src/lib/search-index/state/search-index.actions.ts
Labels: enhancement

#786 HTM-1377: remove dependency track buildsteps tailormap-viewer
  .github/workflows/test-and-deploy.yml
  README.md
Labels: infrastructure

#784 HTM-1370: Change search component lay-out when more than one search index can be used
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.css
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.html
  projects/core/src/lib/components/toolbar/simple-search/simple-search.component.ts
  projects/shared/src/lib/helpers/htmlify.helper.spec.ts
  projects/shared/src/lib/helpers/htmlify.helper.ts
Labels: enhancement

#790 HTM-1397: introduce the task-progress event in the AdminSseService
  projects/admin-core/src/lib/catalog/services/feature-source.service.ts
  projects/admin-core/src/lib/shared/services/admin-sse.service.ts
Labels: enhancement
