Repository Tailormap/tailormap-viewer, pull requests merged in 2024-06, with the labels that each got.

#641 [HTM-1114] Feature-info text not broken properly when text in attribute is long
  projects/core/src/lib/components/edit/edit-dialog/edit-dialog.component.css
  projects/core/src/lib/components/feature-info/feature-info-dialog/feature-info-dialog.component.css
Labels: enhancement

#649 Support high DPI legends for MapServer
  projects/map/src/lib/openlayers-map/open-layers-layer-manager.ts
  projects/shared/src/lib/components/legend-image/legend-image.component.ts
Labels: enhancement

#658 HTM-1131: Traefik Host rule does not support multiple hostnames anymore
  ci/tailormap-embed-test/compose.yaml
Labels: bug

#656 [CI] update COMPOSE_VERSION to 2.27.2
  .github/workflows/test-and-deploy.yml
Labels: infrastucture

#661 Consolidate the 2 Solr profiles into one
  .github/workflows/test-and-deploy.yml
  docker-compose.yml
Labels: infrastucture

#665 HTM-1139: Deploy Solr service on deployment of snapshot
  .github/workflows/test-and-deploy.yml
  docker-compose.yml
Labels: bug

#666 HTM-1140: ♻ Add workflow to deploy `tailormap-embed-test`
  .github/workflows/deploy-embed-test.yml
  ci/tailormap-embed-test/Dockerfile
  ci/tailormap-embed-test/favicon.ico
  ci/tailormap-embed-test/index.html
Labels: infrastucture

#664 HTM-1138: 🇳🇱 Update and fix Dutch translations
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/shared/assets/locale/messages.shared.nl.xlf
Labels: bug

#663 HTM-1137: 🇩🇪 Update and fix German translations
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/core/assets/locale/messages.core.de.xlf
  projects/shared/assets/locale/messages.shared.de.xlf
Labels: bug

#657 Update NodeJS to 20.15.0
  .github/workflows/test-and-deploy.yml
  Dockerfile
Labels: infrastructure, docker-update

#667 HTM-1134: Only add SCALE parameter if legend request is GetLegendGraphic
  projects/core/src/lib/components/legend/services/legend.service.ts
Labels: bug
