Repository Tailormap/tailormap-viewer, pull requests merged in 2024-08, with the labels that each got.

#654 HTM-1126: Use selected layer for layer details + adjusted cursor
  projects/admin-core/src/lib/application/application-layer-tree/application-layer-tree-node/application-layer-tree-node.component.css
  projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.html
  projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.spec.ts
  projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.ts
  projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.css
  projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.html
  projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.ts
  projects/core/src/lib/components/toc/toc/toc.component.css
  projects/core/src/lib/components/toc/toc/toc.component.html
  projects/core/src/lib/components/toc/toc/toc.component.spec.ts
  projects/core/src/lib/components/toc/toc/toc.component.ts
  projects/core/src/lib/map/state/map.selectors.ts
  projects/shared/src/lib/components/tree/tree.component.css
  projects/shared/src/lib/components/tree/tree.component.ts
Labels: enhancement

#682 HTM-1173: Rename docker images to use the new Tailormap organisation
  .all-contributorsrc
  .env.template
  .github/workflows/cleanup-and-maintainance.yml
  .github/workflows/test-and-deploy.yml
  .github/workflows/trivy.yml
  Dockerfile
  README.md
  docker-compose.yml
Labels: infrastructure

#685 HTM-1169: Update tailormap-viewer CI/CD workflows to make them work again
  .github/workflows/cleanup-and-maintainance.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-embed-test.yml
  .github/workflows/process-test-results.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-and-deploy.yml
  .github/workflows/trivy.yml
  README.md
Labels: infrastructure

#687 Bump NodeJS version from 20.16.0 to 20.17.0
  .github/workflows/test-and-deploy.yml
  Dockerfile
Labels: infrastructure

#688 HTM-1197: Bump OpenLayers from 10.0.0 to 10.1.0 and proj4 from 2.11.0 to 2.12.0
  package-lock.json
  package.json
Labels: dependency

#695 Update and rename codeql-analysis.yml to codeql.yml
  .github/workflows/codeql.yml
Labels: infrastructure
