Repository Tailormap/tailormap-viewer, pull requests merged in 2024-04, with the labels that each got.

#606 [HTM-1030] Upgrade OpenLayers to 9.1.0
  package-lock.json
  package.json
Labels: dependencies

#612 Fix PR deployment: remove db container using YAML !reset tag
  .github/workflows/test-and-deploy.yml
  ci/docker-compose.pr.yml
Labels: infrastucture

#615 [HTM-1101] Upgrade NodeJS to current LTS (20.12.2)
  .github/dependabot.yml
  .github/workflows/test-and-deploy.yml
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies, docker-update

#616 HTM-1097: ECQL does not have date only format for time literals
  projects/core/src/lib/filter/helpers/cql-filter.helper.spec.ts
  projects/core/src/lib/filter/helpers/cql-filter.helper.ts
Labels: bug

#571 [HTM-1063] Add preconfigured Solr instance to compose stack
  .github/workflows/test-and-deploy.yml
  README.md
  docker-compose.network.yml
  docker-compose.traefik.yml
  docker-compose.yml
Labels: enhancement
