Repository Tailormap/tailormap-viewer, pull requests merged in 2025-01, with the labels that each got.

#792 HTM-1398: refactor task keys
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/src/lib/tasks/task-details-row/task-details-row.component.ts
Labels: enhancement

#791 HTM-1361: handle index tasks progress events in the admin frontend
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.html
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
Labels: enhancement

#793 HTM-1401 | HTM-1402 | HTM-1404: Update task-progress event to have optional map of task data and use that to show indexing progress
  projects/admin-core/src/lib/search-index/search-index-form/search-index-form.component.ts
  projects/admin-core/src/lib/shared/services/admin-sse.service.ts
Labels: enhancement

#795 HTM-1371: Can't search for values with spaces in them with Solr
  projects/core/src/lib/components/toolbar/simple-search/simple-search.service.ts
Labels: bug

#797 HTM-1408: Added notes to user form
  projects/admin-core/src/lib/user/user-edit/user-edit.component.spec.ts
  projects/admin-core/src/lib/user/user-form/user-form.component.html
  projects/admin-core/src/lib/user/user-form/user-form.component.spec.ts
  projects/admin-core/src/lib/user/user-form/user-form.component.ts
  projects/core/src/lib/shared/components/dialog/dialog.component.html
Labels: enhancement

#801 HTM-1414: Fixes Markdown editor preview
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
  projects/admin-core/src/lib/catalog/feature-type-template/feature-type-template.component.html
  projects/admin-core/src/lib/catalog/feature-type-template/feature-type-template.component.ts
  projects/core/src/lib/components/feature-info/feature-info-template-renderer/feature-info-template-renderer.component.ts
  projects/shared/src/lib/components/markdown-editor/markdown-source-editor/markdown-source-editor.component.html
  projects/shared/src/lib/components/markdown-editor/markdown-source-editor/markdown-source-editor.component.ts
  projects/shared/src/lib/helpers/markdown.helper.spec.ts
  projects/shared/src/lib/helpers/markdown.helper.ts
Labels: bug

#798 Show OIDC role name as group information on group and OIDC registration pages
  projects/admin-api/src/lib/models/additional-property.model.ts
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/admin-core-routing.module.ts
  projects/admin-core/src/lib/oidc/oidc-configuration-edit/oidc-configuration-edit.component.css
  projects/admin-core/src/lib/oidc/oidc-configuration-edit/oidc-configuration-edit.component.html
  projects/admin-core/src/lib/oidc/oidc-configuration-edit/oidc-configuration-edit.component.ts
  projects/admin-core/src/lib/oidc/oidc-configuration-form/oidc-configuration-form.component.html
  projects/admin-core/src/lib/pages/groups-page/groups-page.component.html
  projects/admin-core/src/lib/pages/groups-page/groups-page.component.ts
  projects/admin-core/src/lib/user/group-edit/group-edit.component.spec.ts
  projects/admin-core/src/lib/user/group-form/group-form.component.css
  projects/admin-core/src/lib/user/group-form/group-form.component.html
  projects/admin-core/src/lib/user/group-form/group-form.component.spec.ts
  projects/admin-core/src/lib/user/group-form/group-form.component.ts
Labels: enhancement

#803 HTM-1060: Support i18n in map service requests
  projects/core/src/lib/components/legend/legend/legend.component.spec.ts
  projects/core/src/lib/components/legend/services/legend.service.ts
  projects/core/src/lib/map/services/application-map.service.ts
  projects/map/src/lib/helpers/ol-layer.helper.ts
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/models/wms-layer.model.ts
Labels: enhancement

#805 Fixes HTM-1414 & HTM-1408
  projects/admin-core/src/lib/user/group-form/group-form.component.html
  projects/admin-core/src/lib/user/group-form/group-form.component.ts
  projects/admin-core/src/lib/user/user-form/user-form.component.html
  projects/admin-core/src/lib/user/user-form/user-form.component.ts
  projects/shared/src/lib/components/markdown-editor/markdown-source-editor/markdown-source-editor.component.ts
Labels: bug

#806 HTM-1422: Upgrade Solr from 9.7.0 to 9.8.0
  docker-compose.yml
Labels: docker-update

#807 SUPPORT-14902 | HTM-1424 : Change the tooltip position of the background layer dropdown options to "before" (from default "below")
  projects/shared/src/lib/components/split-button/split-button.component.html
Labels: bug

#811 HTM-1427: admin frontend uses incorrect cron expression for Monday evening
  projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.ts
Labels: bug

#812 Bump OpenLayers from 10.3.1 to 10.4.0
  package-lock.json
  package.json
Labels: dependency
