Repository Tailormap/tailormap-viewer, pull requests merged in 2025-03, with the labels that each got.

#823 Also show primary key icon in application layer attribute settings
  projects/admin-core/src/lib/application/application-layer-attribute-settings/application-layer-attribute-settings.component.html
  projects/admin-core/src/lib/application/application-layer-attribute-settings/application-layer-attribute-settings.component.ts
  projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts
Labels: enhancement

#825 Extended map click event to provide resolution and scale next to coords
  projects/map/src/lib/models/tools/map-click-tool.model.ts
  projects/map/src/lib/openlayers-map/helpers/open-layers.helper.ts
  projects/map/src/lib/openlayers-map/open-layers-tool-manager.spec.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.spec.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.ts
Labels: enhancement

#818 Fixes HTM-1440: only show filterable layers with attributes
  projects/core/src/lib/map/state/map.selectors.ts
Labels: bug

#826 HTM-1453, HTM-1454: Fix catalog node warnings
  projects/admin-core/src/lib/catalog/catalog-base-tree/catalog-base-tree-node/catalog-base-tree-node.component.ts
Labels: bug

#820 HTM-1442: show messages about feature type being editable or not
  projects/admin-api/src/lib/models/feature-type.model.ts
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.spec.ts
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.ts
  projects/admin-core/src/lib/catalog/helpers/extended-catalog-model.helper.ts
  projects/admin-core/src/lib/catalog/models/extended-feature-source.model.ts
  projects/admin-core/src/lib/catalog/state/catalog.selectors.ts
  projects/shared/src/lib/components/error-message/error-message.component.html
  projects/shared/src/lib/components/error-message/error-message.component.ts
Labels: enhancement

#829 HTM-1446: Add configuration for WMS server type
  projects/admin-api/src/lib/mock-data/tailormap-admin-api.mock-data.ts
  projects/admin-api/src/lib/models/admin-server-type.model.ts
  projects/admin-api/src/lib/models/geo-service-settings.model.ts
  projects/admin-api/src/lib/models/index.ts
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/catalog/catalog-create-buttons/catalog-create-buttons.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-details/geo-service-details.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-form-dialog/geo-service-form-dialog.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.css
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.html
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-form/geo-service-form.component.ts
Labels: enhancement

#831 HTM-1189: increase the WMS getFeatureInfo maximum features count from 1 (default) to 10
  projects/map/src/lib/openlayers-map/helpers/open-layers-wms-get-feature-info.helper.ts
Labels: enhancement

#832 HTM-1458: use UUID v4 to create FIDs instead of nanoid
  package-lock.json
  package.json
  projects/core/src/lib/components/drawing/helpers/drawing.helper.ts
Labels: enhancement

#830 Use tailormap tools
  Dockerfile
  bin/.eslintrc.js
  bin/.gitignore
  bin/clear-cache.js
  bin/extract-i18n.js
  bin/generate-protobuf.js
  bin/package-lock.json
  bin/package.json
  bin/post-build-compress.js
  bin/post-build-version-info.js
  bin/publish-all.js
  bin/publish-new-release.js
  bin/shared.js
  package-lock.json
  package.json
  projects/admin-api/package.json
  projects/admin-core/package.json
  projects/api/package.json
  projects/core/package.json
  projects/map/package.json
  projects/shared/package.json
  tm-project.json
Labels: infrastructure

#835 HTM-1464: Update Angular 19 to current patch version
  package-lock.json
  package.json
  projects/admin-core/src/lib/catalog/feature-type-form-dialog/feature-type-form-dialog.component.html
  projects/admin-core/src/lib/catalog/feature-type-form-dialog/feature-type-form-dialog.component.ts
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.ts
Labels: dependency

#837 HTM-1467: update angular-eslint devDependencies to 19 and disable prefer-standalone lint rule
  .eslintrc.json
  package-lock.json
  package.json
Labels: dependency

#838 HTM-1435: Add settings to hide some functionality for layers
  projects/admin-api/src/lib/models/app-layer-settings.model.ts
  projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.html
  projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts
  projects/api/src/lib/models/app-layer.model.ts
  projects/api/src/lib/models/hidden-layer-functionality.model.ts
  projects/api/src/lib/models/index.ts
  projects/core/src/lib/components/attribute-list/attribute-list-export-button/attribute-list-export-button.component.spec.ts
  projects/core/src/lib/components/attribute-list/attribute-list-export-button/attribute-list-export-button.component.ts
  projects/core/src/lib/components/attribute-list/attribute-list/attribute-list.component.ts
  projects/core/src/lib/components/attribute-list/services/attribute-list-manager.service.ts
  projects/core/src/lib/components/feature-info/feature-info.service.ts
Labels: enhancement

#842 HTM-1470: Only show user logged out message in case of unauthorized
  projects/api/src/lib/models/extended-user-response.model.ts
  projects/api/src/lib/services/tailormap-api-v1-mock.service.ts
  projects/api/src/lib/services/tailormap-api-v1.service.model.ts
  projects/api/src/lib/services/tailormap-api-v1.service.spec.ts
  projects/api/src/lib/services/tailormap-api-v1.service.ts
  projects/api/src/lib/services/tailormap-security-api-v1.service.model.ts
  projects/api/src/lib/services/tailormap-security-api-v1.service.ts
  projects/core/src/lib/services/user-login-check.service.ts
Labels: bug

#843 HTM-1470: Ignore (possibly temporary) Ajax errors
  projects/api/src/lib/models/extended-user-response.model.ts
  projects/api/src/lib/services/tailormap-security-api-v1.service.ts
  projects/core/src/lib/services/user-login-check.service.ts
Labels: bug

#845 HTM-1432: Add QR-code and URL of bookmark to print-PDF
  package-lock.json
  package.json
  projects/core/assets/locale/messages.core.de.xlf
  projects/core/assets/locale/messages.core.en.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/core/src/lib/components/print/print.service.ts
  projects/core/src/lib/components/print/print/print.component.html
  projects/core/src/lib/components/print/print/print.component.ts
  projects/core/src/lib/services/map-pdf/map-pdf.service.ts
  projects/core/src/lib/shared/helpers/image.helper.ts
Labels: enhancement

#847 HTM-1489: Fixes click tool always being enabled
  projects/map/src/lib/map-service/map.service.ts
  projects/map/src/lib/openlayers-map/open-layers-event-manager.spec.ts
  projects/map/src/lib/openlayers-map/open-layers-event-manager.ts
  projects/map/src/lib/openlayers-map/open-layers-tool-manager.ts
  projects/map/src/lib/openlayers-map/openlayers-map.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.ts
Labels: bug
