Repository Tailormap/tailormap-viewer, pull requests merged in 2025-06, with the labels that each got.

#893 HTM-1549: restore option to disable any form field
  projects/admin-core/src/lib/form/form-edit-field/form-edit-field.component.html
Labels: bug

#892 HTM-1504: Header component
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/application/components/base-component-config/base-component-config.component.ts
  projects/admin-core/src/lib/application/components/components.module.ts
  projects/admin-core/src/lib/application/components/coordinate-link-window-config/coordinate-link-window-component-config.component.ts
  projects/admin-core/src/lib/application/components/feature-info-config/feature-info-component-config.component.ts
  projects/admin-core/src/lib/application/components/header-config/header-component-config.component.css
  projects/admin-core/src/lib/application/components/header-config/header-component-config.component.html
  projects/admin-core/src/lib/application/components/header-config/header-component-config.component.ts
  projects/admin-core/src/lib/application/components/header-config/header-component-logo-remove.service.ts
  projects/admin-core/src/lib/application/components/measure-config/measure-component-config.component.ts
  projects/admin-core/src/lib/application/components/simple-search-config/simple-search-component-config.component.ts
  projects/admin-core/src/lib/application/services/component-configuration.service.ts
  projects/api/src/lib/models/base-component-type.enum.ts
  projects/api/src/lib/models/component-config/header-component-config.model.ts
  projects/api/src/lib/models/component-config/index.ts
  projects/core/assets/icons/menu.svg
  projects/core/src/lib/components/components.module.ts
  projects/core/src/lib/components/header/header.module.ts
  projects/core/src/lib/components/header/header/header.component.css
  projects/core/src/lib/components/header/header/header.component.html
  projects/core/src/lib/components/header/header/header.component.ts
  projects/core/src/lib/components/header/header/header.helper.ts
  projects/core/src/lib/components/header/index.ts
  projects/core/src/lib/components/menubar/menubar.component.html
  projects/core/src/lib/components/menubar/menubar.component.ts
  projects/core/src/lib/layout/base-layout/base-layout.component.css
  projects/core/src/lib/layout/base-layout/base-layout.component.html
  projects/core/src/lib/layout/embedded-layout/embedded-layout.component.css
  projects/core/src/lib/pages/viewer-app/viewer-app.component.css
  projects/core/src/lib/pages/viewer-app/viewer-app.component.html
  projects/shared/src/lib/helpers/css.helper.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#897 HTM-1556: Do not save irrelevant values in slider config
  projects/admin-core/src/lib/application/application-edit-filters/application-slider-filter-form/application-slider-filter-form.component.ts
Labels: bug

#899 HTM-1504: Header component bugfixes
  projects/admin-core/src/lib/application/components/header-config/header-component-config.component.ts
  projects/api/src/lib/helpers/base-component-config.helper.ts
  projects/core/assets/icons/fullscreen.svg
  projects/core/assets/icons/fullscreen_exit.svg
  projects/core/assets/locale/messages.core.de.xlf
  projects/core/assets/locale/messages.core.en.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/core/assets/tailormap-styles.css
  projects/core/src/lib/components/header/header/header.component.css
  projects/core/src/lib/components/header/header/header.component.ts
  projects/core/src/lib/components/menubar/menubar.component.html
  projects/core/src/lib/components/menubar/menubar.component.ts
  projects/core/src/lib/layout/base-layout/base-layout.component.html
  projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.css
  projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.html
  projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.spec.ts
  projects/core/src/lib/shared/components/bottom-panel/bottom-panel.component.ts
Labels: bug

#906 HTM-1535: Show filter icon in toc for filtered layers
  projects/core/assets/locale/messages.core.de.xlf
  projects/core/assets/locale/messages.core.en.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/core/src/lib/components/filter/filter-list-item/filter-list-item.component.html
  projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.css
  projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.html
  projects/core/src/lib/components/toc/toc-node-layer/toc-node-layer.component.ts
  projects/core/src/lib/components/toc/toc/toc.component.html
  projects/core/src/lib/components/toc/toc/toc.component.spec.ts
  projects/core/src/lib/components/toc/toc/toc.component.ts
  projects/core/src/lib/filter/state/filter.selectors.ts
Labels: enhancement

#911 HTM-1572: Allow deselection of element that was just drawn
  projects/core/src/lib/map/services/drawing.service.ts
  projects/core/src/lib/test-helpers/map-service.mock.spec.ts
  projects/map/src/lib/models/tools/select-tool.model.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-select-tool.ts
Labels: bug

#910 HTM-1567: Show buffer when modifying filter geometry.
  projects/api/src/lib/models/feature.model.ts
  projects/core/src/lib/components/filter/services/filter-features.service.ts
  projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.html
  projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.spec.ts
  projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.ts
  projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.html
  projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.spec.ts
  projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.ts
  projects/core/src/lib/components/filter/state/filter-component.actions.ts
  projects/core/src/lib/components/filter/state/filter-component.reducer.ts
  projects/core/src/lib/components/filter/state/filter-component.selectors.ts
  projects/core/src/lib/components/filter/state/filter-component.state.ts
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.ts
  projects/map/src/lib/helpers/buffer.helper.ts
  projects/map/src/lib/helpers/map-style.helper.ts
  projects/map/src/lib/models/map-style.model.ts
  projects/map/src/public-api.ts
  projects/map/src/typings.d.ts
  setup-jest.ts
Labels: bug

#914 HTM-1578: Upgrade OpenLayers from 10.5.0 to 10.6.1, PROJ4JS from 2.15.0 to 2.19.3, ol-ext from 4.0.31 to 4.0.33
  package-lock.json
  package.json
Labels: dependencies

#919 EK-48: Add IMAGE featuretype and related styling options for advanced drawing
  projects/core/src/lib/components/drawing/drawing-style-form/drawing-style-form.component.ts
  projects/core/src/lib/components/drawing/models/drawing-feature.model.ts
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.ts
  projects/core/src/lib/map/models/drawing-feature-type.enum.ts
  projects/core/src/lib/map/services/drawing.service.ts
Labels: enhancement
