Repository Tailormap/tailormap-viewer, pull requests merged in 2025-02, with the labels that each got.

#813 HTM-1430: Add warning messages when a feature type does not have a primary key and/or geometry attribute
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
Labels: enhancement

#815 HTM-1388: Remove `jsdom-worker` dev dependency after OpenLayers upgrade
  jest.base.config.js
  package-lock.json
  package.json
Labels: dependency

#819 HTM-1443: show key icon next to primary key attribute
  projects/admin-core/assets/locale/messages.admin-core.de.xlf
  projects/admin-core/assets/locale/messages.admin-core.en.xlf
  projects/admin-core/assets/locale/messages.admin-core.nl.xlf
  projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.html
  projects/admin-core/src/lib/catalog/feature-type-attributes/feature-type-attributes.component.ts
  projects/admin-core/src/lib/catalog/feature-type-form/feature-type-form.component.html
Labels: enhancement

#821 ⛓️‍💥 EK-15: replace the PostgreSQL 15 image with a PostGIS 17-3.5 image ⛓️‍💥
  .github/dependabot.yml
  docker-compose.yml
Labels: enhancement, infrastructure, docker-update, breaking
