Repository Tailormap/tailormap-viewer, pull requests merged in 2025-04, with the labels that each got.

#850 EK-41: Add a toGeoJSON(olGeometry) function
  projects/map/src/lib/helpers/feature.helper.ts
Labels: enhancement

#849 EK-7: Enable modify tool for drawing features
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.html
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.spec.ts
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.ts
  projects/core/src/lib/components/drawing/state/drawing.actions.ts
  projects/core/src/lib/components/drawing/state/drawing.reducer.ts
  projects/core/src/lib/components/drawing/state/drawing.selectors.ts
  projects/core/src/lib/components/filter/services/spatial-filter-crud.service.ts
  projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.html
  projects/core/src/lib/components/filter/spatial-filter-form-draw-geometries/spatial-filter-form-draw-geometries.component.ts
  projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.html
  projects/core/src/lib/components/filter/spatial-filter-form/spatial-filter-form.component.ts
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.html
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.spec.ts
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.ts
  projects/map/src/lib/models/tool-manager.model.ts
  projects/map/src/lib/models/tools/modify-tool.model.ts
  projects/map/src/lib/openlayers-map/open-layers-tool-manager.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-modify-tool.ts
Labels: enhancement

#848 HTM-1468: Refactor The Coordinate Picker Tool with navigation functionality
  projects/core/assets/locale/messages.core.de.xlf
  projects/core/assets/locale/messages.core.en.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.css
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.html
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.spec.ts
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.ts
  projects/core/src/lib/layout/layout.service.ts
Labels: enhancement

#846 Save correct index for 3D tiles layers
  projects/map/src/lib/openlayers-map/cesium-map/cesium-manager.ts
Labels: bug

#852 HTM-1495: Update OpenLayers to 10.5.0
  package-lock.json
  package.json
  projects/map/package.json
  projects/map/src/lib/openlayers-map/open-layers-event-manager.ts
Labels: dependencies

#854 EK-43: Add support for circle geometries in the GeoJSON converter functions
  projects/map/src/lib/helpers/feature.helper.spec.ts
  projects/map/src/lib/helpers/feature.helper.ts
Labels: enhancement

#858 HTM-1468: Refactor The Coordinate Picker Tool with navigation functionality (take 2)
  projects/core/assets/icons/show_position.svg
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.css
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.html
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#860 HTM-1492: Hide opacity slider in layer details in TOC for 3D Tiles
  projects/core/src/lib/components/toc/toc-node-details/layer-details/layer-details.component.html
  projects/core/src/lib/components/toc/toc-node-details/layer-details/layer-details.component.ts
  projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.html
  projects/core/src/lib/components/toc/toc-node-details/toc-node-details.component.ts
  projects/core/src/lib/map/models/layer-tree-node-with-layer.model.ts
  projects/core/src/lib/map/state/map.selectors.ts
Labels: bug

#859 HTM-1482: Use tileLoadFunction to support TileWMS in 3D
  projects/map/src/lib/helpers/ol-layer.helper.ts
  projects/map/src/lib/openlayers-map/open-layers-layer-manager.ts
Labels: bug

#863 Improved modify tool, remove toggle, edit vertices and size/position
  projects/core/assets/icons/copy.svg
  projects/core/assets/icons/copy_filled.svg
  projects/core/assets/icons/copy_outline.svg
  projects/core/assets/icons/remove.svg
  projects/core/assets/icons/remove_all.svg
  projects/core/assets/icons/tools/modify_translate.svg
  projects/core/assets/icons/tools/vertices.svg
  projects/core/assets/icons/zoom_max.svg
  projects/core/assets/locale/messages.core.de.xlf
  projects/core/assets/locale/messages.core.en.xlf
  projects/core/assets/locale/messages.core.nl.xlf
  projects/core/src/lib/components/drawing/create-drawing-button/create-drawing-button.component.spec.ts
  projects/core/src/lib/components/drawing/drawing/drawing.component.css
  projects/core/src/lib/components/drawing/drawing/drawing.component.html
  projects/core/src/lib/components/filter/filter-list-item/filter-list-item.component.html
  projects/core/src/lib/components/toolbar/clicked-coordinates/clicked-coordinates.component.html
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.html
  projects/core/src/lib/map/components/map-drawing-buttons/map-drawing-buttons.component.ts
  projects/map/src/lib/models/tools/ext-transform-tool.model.ts
  projects/map/src/lib/openlayers-map/tools/open-layers-ext-transform-tool.ts
  projects/shared/src/lib/services/icons/icon.service.ts
Labels: enhancement

#861 HTM-1481: Stop re-rendering entire map in 3D when a layer changes
  projects/map/src/lib/openlayers-map/cesium-map/cesium-manager.ts
Labels: bug

#864 HTM-1514: Request render for 3D scene after 2D layers change
  projects/map/src/lib/openlayers-map/cesium-map/cesium-manager.ts
Labels: bug

#870 HTM-1509: Show whether layers are available in the relevant projections
  projects/admin-core/assets/icons/admin/unavailable.svg
  projects/admin-core/src/lib/admin-core.module.ts
  projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.css
  projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.html
  projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts
  projects/admin-core/src/lib/application/helpers/admin-projections-helper.ts
  projects/admin-core/src/lib/catalog/catalog.module.ts
  projects/admin-core/src/lib/catalog/geo-service-layer-details/geo-service-layer-details.component.html
  projects/admin-core/src/lib/catalog/geo-service-layer-details/geo-service-layer-details.component.spec.ts
  projects/admin-core/src/lib/catalog/geo-service-layer-details/geo-service-layer-details.component.ts
  projects/admin-core/src/lib/catalog/layer-settings-form/layer-settings-form.component.css
  projects/admin-core/src/lib/catalog/layer-settings-form/layer-settings-form.component.html
  projects/admin-core/src/lib/catalog/layer-settings-form/layer-settings-form.component.ts
  projects/admin-core/src/lib/catalog/projection-availability/projection-availability.component.css
  projects/admin-core/src/lib/catalog/projection-availability/projection-availability.component.html
  projects/admin-core/src/lib/catalog/projection-availability/projection-availability.component.spec.ts
  projects/admin-core/src/lib/catalog/projection-availability/projection-availability.component.ts
Labels: bug
